version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/h3poteto/kubebuilder:2.3.1
    working_directory: /go/src/github.com/h3poteto/kms-secrets
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - mod-{{ arch }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run:
          name: Install
          command: go mod download
      - save_cache:
          name: Save cache
          key: mod-{{ arch }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Test
          command: ginkgo -r ./

  create_latest_image:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: |
            docker build -t h3poteto/kms-secrets:latest -t h3poteto/kms-secrets:${CIRCLE_SHA1} .
      - run:
          name: push
          command: |
            docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
            docker push h3poteto/kms-secrets:latest
            docker push h3poteto/kms-secrets:${CIRCLE_SHA1}
  create_tag_image:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: |
            docker build -t h3poteto/kms-secrets:${CIRCLE_TAG} .
      - run:
          name: push
          command: |
            docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
            docker push h3poteto/kms-secrets:${CIRCLE_TAG}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - create_latest_image:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - create_tag_image:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
