# permissions for end users to view kmssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmssecret-viewer-role
rules:
- apiGroups:
  - secret.h3poteto.dev
  resources:
  - kmssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.h3poteto.dev
  resources:
  - kmssecrets/status
  verbs:
  - get
