# permissions for end users to edit kmssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmssecret-editor-role
rules:
- apiGroups:
  - secret.h3poteto.dev
  resources:
  - kmssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.h3poteto.dev
  resources:
  - kmssecrets/status
  verbs:
  - get
