apiVersion: secret.h3poteto.dev/v1beta1
kind: KMSSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    API_KEY: # KMS encrypted string
    PASSWORD: #KMS encrypted string
  # AWS region where the KMS key is located
  region: ap-northeast-1
  template:
    metadata:
      labels:
        "h3poteto.dev/labels-test": enabeld
      annotations:
        "h3poteto.dev/annotations-test": disabled
